# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_auto_20170921_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='celebrity',
            new_name='celebrities',
        ),
    ]
